### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by ghost** [miu200521358/pmx_dressup#9]
I tried to use this tool and I get is this error when I set it up

```
■■■■■■■■■■■■■■■■■
■　** CRITICAL **  
■　An unexpected error has occurred
■■■■■■■■■■■■■■■■■
Traceback (most recent call last):
  File "mlib\\service\\base_worker.py", line 124, in mlib.service.base_worker.BaseWorker.run
  File "service\worker\load_worker.py", line 118, in thread_execute
  File "mlib\\pmx\\pmx_collection.py", line 1266, in mlib.pmx.pmx_collection.PmxModel.replace_standard_weights
  File "mlib\\core\\collection.py", line 113, in mlib.core.collection.BaseIndexNameDictModel.__getitem__
  File "mlib\\core\\collection.py", line 282, in mlib.core.collection.BaseIndexNameDictModel.get_by_name
KeyError: '右腕捩'
Stack (most recent call last):
  File "threading.py", line 995, in _bootstrap
  File "threading.py", line 1038, in _bootstrap_inner
```

Currently using the PmxDressup_1.00.00_β44 version I downloaded from Bowlroll.

**Comment by ghost** [comment]
Update, so it may be the costume, I used a different costume and it worked.


I have no idea what exactly is the problem however.

I know this is in beta but this is frustrating.

The model does not have any right arm bones because it did not have any mesh on that side.

**Comment by Ry3yr** [comment]
This occurs sometimes.

I usually use different bones to fix it.

You can use pmxinfo too to see if your target model has illegal bones or morphs.

PmxDressup has issues with those

Great tool still, fixes many things
